-- Professor Doctor
--
--   22-METsaysTHANKS!   22-MET    says
-- THANKS!22-MET         says     THANKS!
--22-MET                 says     THANKS!
-- 22-MET                says               THANKS!22-METsays
--  THANKS!              22-M     ETsays    THANKS!22-METsays
--   THANKS!22-          METs     aysTHA    NKS!  22-M  ETsay
--    sTHANKS!22-        METs     aysTHA    NKS!  22-M  ETsay
--     sTHANKS!22-M      ETsa     ysTHAN    KS!2  2-ME  Tsays
--    THANKS!22-MET      says     THANKS    !22-  METs  aysTH
--ANKS!22-METsays       THANKS!  22-METsa   ysTH  ANKS  !!!!!!
-----------------------------------------------------------------
main=putStrLn(w s t);w p q=q++show p++";t="++show q;s="-- Professor Doctor\n--\n--   22-METsaysTHANKS!   22-MET    says\n-- THANKS!22-MET         says     THANKS!\n--22-MET                 says     THANKS!\n-- 22-MET                says               THANKS!22-METsays\n--  THANKS!              22-M     ETsays    THANKS!22-METsays\n--   THANKS!22-          METs     aysTHA    NKS!  22-M  ETsay\n--    sTHANKS!22-        METs     aysTHA    NKS!  22-M  ETsay\n--     sTHANKS!22-M      ETsa     ysTHAN    KS!2  2-ME  Tsays\n--    THANKS!22-MET      says     THANKS    !22-  METs  aysTH\n--ANKS!22-METsays       THANKS!  22-METsa   ysTH  ANKS  !!!!!!\n-----------------------------------------------------------------\nmain=putStrLn(w s t);w p q=q++show p++\";t=\"++show q;s=";t="-- 22-MET Says\n--\n-- 22-METsaysTHANKS!   22-MET    says    THANKS!      22-MET\n-- saysTHANKS!22-MET   saysTH    ANKS      !22-MET   says\n--     THANKS!         22-MET    says        THANKS! 22-\n--     METsays         THANKS!!!!22-M           ETsays\n--     THANKS!         22-METsaysTHAN         KS!22-MET\n--     saysTHA         NKS!22    -MET      saysTH   ANKS!\n--     22--MET         saysTH    ANKS    !22-MET     says\n--    THANKS!22       -METsays  THANKS  ForEvery     Thing!!\n-----------------------------------------------------------------\n----------------------- PS: Run me ;) ---------------------------\nmain=putStrLn(w s t);w p q=p++show p++\";t=\"++show q;s="
